import './pwi-accessible-textfield.js';
import './pwi-accessible-textarea.js';
import './pwi-accessible-date.js';
import './pwi-accessible-email.js';
import './pwi-accessible-number.js';
import './pwi-accessible-locale.js';
import './pwi-accessible-locale-form.js';
import './pwi-accessible-select.js';
import './pwi-accessible-tel.js';
